server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:postgresql://localhost:5432/multitenancy?ApplicationName=MultiTenant'
    username: 'user'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
tenants: public, test1, test2
default-tenant: public
